name: Build Solution

on:
  workflow_call:
    inputs:
      branch-postfix:
        required: false
        type: string
      game:
        required: true
        type: string
    secrets:
      REPO_ACCESS_TOKEN:
        required: true

jobs:
  build:
    name: Build Oxide Solution
    runs-on: windows-2022

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Solution
        uses: ./.github/actions/build-solution
        with:
          project-name: Oxide.${{ inputs.game }}
          branch-postfix: ${{ inputs.branch-postfix }}
          repo-token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Compress Bundles
        run: |
          foreach ($directory in Get-ChildItem -Path src\bin\Bundle -Directory)
          {
            7z a "$($directory.FullName).zip" "$($directory.FullName)/*"
          }

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}
          path: src\bin\Bundle\Oxide.*.zip

      - name: Upload Docs
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-docs
          path: docs\docs.json
