name: Build and Deploy

on:
  workflow_call:
    inputs:
      branch-postfix:
        required: false
        type: string
      project-name:
        required: true
        type: string
      version-prefix:
        required: true
        type: string
    secrets:
      REPO_ACCESS_TOKEN:
        required: true
      MYGET_API_KEY:
        required: true
      DISCORD_WEBHOOK:
        required: true

env:
  BUILD: ${{ github.ref_name == 'master' && 'Release' || 'Debug' }}

jobs:
  build:
    name: Build and Deploy
    runs-on: windows-2022

    outputs:
      version: ${{ steps.build.outputs.version }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Solution
        id: build
        uses: ads102003/Actions/.github/actions/build-solution@main
        with:
          project-name: ${{ inputs.project-name }}
          branch-postfix: ${{ inputs.branch-postfix }}
          repo-token: ${{ secrets.REPO_ACCESS_TOKEN }}
          version-prefix: ${{ inputs.version-prefix }}
          version: ${{ vars.VERSION }}
          build-configuration: ${{ env.BUILD }}
        env:
          BUILD: ${{ env.BUILD }}

      - name: Upload Artifacts
        if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop')
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}
          path: src/bin/${{ env.BUILD }}/

      - name: Package NuGet
        if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop')
        run: |
          Get-ChildItem "src\bin\${{env.BUILD}}" -Recurse *.nupkg | ForEach-Object {
            echo "Found NuGet package: $($_.FullName)"
            echo "PACKAGE_PATH=$($_.FullName)" >> $env:GITHUB_ENV
          }

      - name: Push to MyGet
        if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop')
        run: |
          dotnet nuget push "${{ env.PACKAGE_PATH }}" --source "${{vars.MYGET_SOURCE_URL}}" --api-key "${{ secrets.MYGET_API_KEY }}"

  notification:
    name: Notify Discord
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
      - name: Discord Notification
        uses: ads102003/Actions/.github/actions/discord-notify@main
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          version: ${{ needs.build.outputs.version }}
          status: ${{ needs.build.result }}
